version: '3.8'

services:
  rentify:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/rental.db
      - UPLOADS_PATH=/app/data/uploads
      - CONTRACTS_PATH=/app/data/contracts
      - RECEIPTS_PATH=/app/data/receipts
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - SMTP_HOST=localhost
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_FROM=noreply@yourdomain.com
      - APP_URL=http://localhost:3000
      - ADMIN_EMAIL=admin@yourdomain.com
      - ADMIN_PASSWORD=admin123
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Local SMTP server for testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped
